### PR TITLE
Logical combinations

### PR DESCRIPTION
**Pull request by swapnilnawale**
Added support for logical combination flags. PR includes a unit test ported from hyperscan library: https://github.com/intel/hyperscan/blob/master/unit/hyperscan/logical_combination.cpp#L480

### CODE REVIEW

**Comment by gliwka** [comment]
Thanks for the contribution. I'll give it a test-drive next Tuesday.

I'm planing to release it next week together with #53.

**Comment by gliwka** [comment]
Looks good to me, thank you and your company for investing the time :-)

**Comment by swapnilnawale** [comment]
Great, thank you too for reviewing the PR.

**Comment by gliwka** [comment]
@swapnilnawale v1.0.0 has been released with this change

**Comment by swapnilnawale** [comment]
Awesome, thank you very much!

**Pull request merged**
