### PR TITLE
Update README to reflect JNA->JavaCPP change

### PR DESCRIPTION
**Pull request by elmart-devo**
It took me some time to realize project was not using JNA anymore. So let's save that for others.
BTW, how much faster is it now? Does it really compare to manually coded JNI?

Thanks very much, keep up your hard work.

### CODE REVIEW

**Comment by gliwka** [comment]
From my limited benchmark in my own use cases, the performance is about the same. There was some noticeable lock contention with JNA on high thread (64 cores) counts, which I didn‘t observe with JavaCPP.

The main advantage and reason for the switch is the code generation, which will make it easier to reach a 100% coverage of the hyperscan API in the following weeks.

**Comment by gliwka** [comment]
Be aware, that the JavaCPP change has not been released yet. I want to complete the API first.

**Comment by elmart-devo** [comment]
> Be aware, that the JavaCPP change has not been released yet. I want to complete the API first.

Yes, yes, I understand. But `pom.xml` in `main` branch already contains `JavaCPP` dep... (that's how I realized about the change).
So, should I close this?
BTW, why such an inoffensive change makes some checks fail?
Thx for your answers.

**Comment by gliwka** [comment]
Leave it open so I don‘t forget to fix the README.

There is a performance regression test as part of the CI test suite, which is a little bit flakey. I have to think about how to fix that (i.e. run on my own non-shared infrastructure).

**Pull request closed without merging**
